spring.application.name=shoppinglist
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.response-mime-type=text/plain

spring.ai.retry.max-attempts=3
spring.ai.retry.back-off.initial-interval=2000
spring.ai.retry.back-off.multiplier=2

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.apache.coyote.http11=DEBUG